apiVersion: apps/v1
kind: Deployment
metadata:
  name: pear-geocode-deployment
  labels:
    app: pear-geocode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pear-geocode
  template:
    metadata:
      labels:
        app: pear-geocode
    spec:
      containers:
        - name: pear-geocode
          imagePullPolicy: IfNotPresent
          image: host.minikube.internal:5000/pear_geocode_service
          ports:
            - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: pear-geocode-service
spec:
  type: NodePort
  selector:
    app: pear-geocode
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30008
